=== Karmel0x/LeagueEmulatorJS/apps/gameserver/src/game/game.config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Omit<PlayerConfig,\"owner\"|\"num\">": {
            "properties": {
                "masteries": {
                    "items": {
                        "type": "number"
                    },
                    "type": "array"
                },
                "match": {
                    "properties": {
                        "champion": {
                            "type": "string"
                        },
                        "skin": {
                            "type": "number"
                        },
                        "team": {
                            "$ref": "#/definitions/TeamId"
                        }
                    },
                    "type": "object"
                },
                "runes": {
                    "items": {
                        "type": "number"
                    },
                    "type": "array"
                },
                "summoner": {
                    "properties": {
                        "iconId": {
                            "type": "number"
                        },
                        "id": {
                            "type": "number"
                        },
                        "level": {
                            "type": "number"
                        },
                        "name": {
                            "type": "string"
                        },
                        "rankId": {
                            "type": "number"
                        },
                        "ribbonId": {
                            "type": "number"
                        },
                        "spells": {
                            "properties": {
                                "d": {
                                    "type": "string"
                                },
                                "f": {
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                }
            },
            "type": "object"
        },
        "TeamId": {
            "enum": [
                -100,
                0,
                100,
                200,
                300
            ],
            "type": "number"
        }
    },
    "properties": {
        "debugging": {
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "noPathFinding": {
                    "type": "boolean"
                },
                "noSpawners": {
                    "type": "boolean"
                },
                "noTerrainEscape": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "game": {
            "properties": {
                "map": {
                    "type": "number"
                },
                "version": {
                    "type": "number"
                }
            },
            "type": "object"
        },
        "logging": {
            "properties": {
                "debug": {
                    "enum": [
                        "console",
                        "file",
                        "none",
                        "websocket"
                    ],
                    "type": "string"
                },
                "packet": {
                    "enum": [
                        "console",
                        "file",
                        "none",
                        "websocket"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "players": {
            "items": {
                "$ref": "#/definitions/Omit%3CPlayerConfig%2C%22owner%22%7C%22num%22%3E"
            },
            "type": "array"
        },
        "server": {},
        "testing": {
            "properties": {
                "adminCommands": {
                    "type": "boolean"
                },
                "bringHeroesToLine": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "levelUpPlayers": {
                    "type": "number"
                },
                "noAutoGameStart": {
                    "type": "boolean"
                },
                "noCooldowns": {
                    "type": "boolean"
                },
                "noHeroDying": {
                    "type": "boolean"
                },
                "noManaCosts": {
                    "type": "boolean"
                },
                "noSpellRangeCheck": {
                    "type": "boolean"
                },
                "spawnMinionsLine": {
                    "type": "number"
                },
                "startingGold": {
                    "type": "number"
                },
                "wavesInitialTimeToSpawn": {
                    "type": "number"
                }
            },
            "type": "object"
        }
    },
    "type": "object"
}

=== Karmel0x/LeagueEmulatorJS/apps/gameserver/src/game/game.config.json
{
	"$schema": "./game.config.schema.json",
	"server": {
		"port": 5119,
		"host": "127.0.0.1"
	},
	"game": {
		"version": 4.20,
		"map": 1,
		"id": 1
	},
	"testing": {
		"enabled": true,
		"adminCommands": true,
		"noCooldowns": true,
		"noManaCosts": true,
		"noHeroDying": true,
		"noSpellRangeCheck": false,
		"spawnMinionsLine": 5,
		"bringHeroesToLine": true,
		"levelUpPlayers": 6,
		"noAutoGameStart": true,
		"wavesInitialTimeToSpawn": 1,
		"startingGold": 47500
	},
	"debugging": {
		"enabled": true,
		"noTerrainEscape": false,
		"noPathFinding": true,
		"noNavmeshVision": false,
		"noGrassCheck": false,
		"noSpawners": false,
		"chatDebugMessages": true
	},
	"logging": {
		"debug": "console",
		"packet": "websocket"
	},
	"players": [
		{
			"summoner": {
				"id": 1,
				"name": "Player1",
				"level": 30,
				"iconId": 666,
				"rankId": 0,
				"ribbonId": 0,
				"spells": {
					"d": "SummonerHeal",
					"f": "SummonerFlash"
				}
			},
			"match": {
				"team": 100,
				"champion": "Ahri",
				"skin": 0
			},
			"runes": [],
			"talents": []
		},
		{
			"summoner": {
				"id": 2,
				"name": "Player2",
				"level": 30,
				"iconId": 666,
				"rankId": 0,
				"ribbonId": 0,
				"spells": {
					"d": "SummonerSmite",
					"f": "SummonerBoost"
				}
			},
			"match": {
				"team": 200,
				"champion": "Ezreal",
				"skin": 0
			},
			"runes": [],
			"talents": []
		},
		{
			"summoner": {
				"id": 3,
				"name": "Player3",
				"level": 30,
				"iconId": 666,
				"rankId": 0,
				"ribbonId": 0,
				"spells": {
					"d": "SummonerHeal",
					"f": "SummonerFlash"
				}
			},
			"match": {
				"team": 100,
				"champion": "Yasuo",
				"skin": 0
			},
			"runes": [],
			"talents": []
		}
	]
}
